### PR TITLE
Fix project building problem and update ExcellentEnchants and Nightcore dependencies

### PR DESCRIPTION
**Pull request by new1271**
a pull request to resolve the building problem i encountered

### Change List
- Uses CodeMC-NMS Maven Repo to provide `org.bukkit.craftbukkit` package
- Changes ViaVersion Repo from `https://repo.viaversion.com/everything` to `https://repo.viaversion.com/` (old url is not available)
- Changes ViaVersion package id from `com.github.MylesIsCool.ViaVersion` to `com.viaversion.viaversion-api` and changes the package version from `4.6.2` to `[5.0.0,6.0.0)`(from ViaVersion readme)
- Changes ProtocolLib's version from `5.2.1-SNAPSHOT`(currently not available) to `5.3.0`(1.20.5+) and `5.2.0-SNAPSHOT`(1.20.4 and below)
- Update ExcellentEnchant dependency (4.2.1 -> 4.2.2)
- Update nightcore dependency (2.6.3 -> 2.6.4)
- Remove duplicate `net.kyori.adventure-text-serializer-gson` reference in `InteractiveChat-Abstraction` project

### CODE REVIEW

**Comment by NotAlexNoyle** [comment]
Gets further in the build than the main branch, but still fails at 1.18.2 for me:

`[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] InteractiveChat-Parent ............................. SUCCESS [  0.130 s]
[INFO] InteractiveChat-Abstraction ........................ SUCCESS [  4.563 s]
[INFO] InteractiveChat-V1_8 ............................... SUCCESS [  4.496 s]
[INFO] InteractiveChat-V1_8_3 ............................. SUCCESS [  1.368 s]
[INFO] InteractiveChat-V1_8_4 ............................. SUCCESS [  1.348 s]
[INFO] InteractiveChat-V1_9 ............................... SUCCESS [  2.224 s]
[INFO] InteractiveChat-V1_9_4 ............................. SUCCESS [  0.925 s]
[INFO] InteractiveChat-V1_10 .............................. SUCCESS [  2.042 s]
[INFO] InteractiveChat-V1_11 .............................. SUCCESS [  1.050 s]
[INFO] InteractiveChat-V1_12 .............................. SUCCESS [  1.956 s]
[INFO] InteractiveChat-V1_13 .............................. SUCCESS [  1.923 s]
[INFO] InteractiveChat-V1_13_1 ............................ SUCCESS [  0.944 s]
[INFO] InteractiveChat-V1_14 .............................. SUCCESS [  0.846 s]
[INFO] InteractiveChat-V1_15 .............................. SUCCESS [  0.873 s]
[INFO] InteractiveChat-V1_16 .............................. SUCCESS [  4.028 s]
[INFO] InteractiveChat-V1_16_2 ............................ SUCCESS [  3.728 s]
[INFO] InteractiveChat-V1_16_4 ............................ SUCCESS [  3.615 s]
[INFO] InteractiveChat-V1_17 .............................. SUCCESS [  4.346 s]
[INFO] InteractiveChat-V1_18 .............................. SUCCESS [  6.209 s]
[INFO] InteractiveChat-V1_18_2 ............................ FAILURE [  0.708 s]
[INFO] InteractiveChat-V1_19 .............................. SKIPPED
[INFO] InteractiveChat-V1_19_3 ............................ SKIPPED
[INFO] InteractiveChat-V1_19_4 ............................ SKIPPED
[INFO] InteractiveChat-V1_20 .............................. SKIPPED
[INFO] InteractiveChat-V1_20_2 ............................ SKIPPED
[INFO] InteractiveChat-V1_20_3 ............................ SKIPPED
[INFO] InteractiveChat-V1_20_5 ............................ SKIPPED
[INFO] InteractiveChat-V1_20_6 ............................ SKIPPED
[INFO] InteractiveChat-V1_21 .............................. SKIPPED
[INFO] InteractiveChat-V1_21_1 ............................ SKIPPED
[INFO] InteractiveChat .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 47.536 s
[INFO] Finished at: 2024-10-20T19:42:13+00:00
[INFO] Final Memory: 98M/404M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project InteractiveChat-V1_18_2: Could not resolve dependencies for project com.loohp:InteractiveChat-V1_18_2:jar:4.2.12.0: Could not find artifact org.bukkit:craftbukkit:jar:1.18.2-R0.1-SNAPSHOT in dmulloy2-repo (https://repo.dmulloy2.net/repository/public/) -> [Help 1]
`

**Comment by new1271** [comment]
@NotAlexNoyle problem fixed

**Comment by NotAlexNoyle** [comment]
> @NotAlexNoyle problem fixed

Working now. thanks!

**Comment by LOOHP** [comment]
Sorry for the late response as I am very very very busy lately but thank you for your PR. I'll take a look and sort it out along with the 1.21.2 update.

**Comment by NotAlexNoyle** [comment]
Correction: almost works:

```[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] InteractiveChat-Parent ............................. SUCCESS [  0.098 s]
[INFO] InteractiveChat-Abstraction ........................ SUCCESS [ 12.996 s]
[INFO] InteractiveChat-V1_8 ............................... SUCCESS [  1.192 s]
[INFO] InteractiveChat-V1_8_3 ............................. SUCCESS [  1.336 s]
[INFO] InteractiveChat-V1_8_4 ............................. SUCCESS [  1.190 s]
[INFO] InteractiveChat-V1_9 ............................... SUCCESS [  2.132 s]
[INFO] InteractiveChat-V1_9_4 ............................. SUCCESS [ 18.167 s]
[INFO] InteractiveChat-V1_10 .............................. SUCCESS [  4.674 s]
[INFO] InteractiveChat-V1_11 .............................. SUCCESS [  3.779 s]
[INFO] InteractiveChat-V1_12 .............................. SUCCESS [  7.346 s]
[INFO] InteractiveChat-V1_13 .............................. SUCCESS [ 25.909 s]
[INFO] InteractiveChat-V1_13_1 ............................ SUCCESS [  0.788 s]
[INFO] InteractiveChat-V1_14 .............................. SUCCESS [  3.271 s]
[INFO] InteractiveChat-V1_15 .............................. SUCCESS [  0.781 s]
[INFO] InteractiveChat-V1_16 .............................. SUCCESS [ 47.166 s]
[INFO] InteractiveChat-V1_16_2 ............................ SUCCESS [  1.257 s]
[INFO] InteractiveChat-V1_16_4 ............................ SUCCESS [  1.613 s]
[INFO] InteractiveChat-V1_17 .............................. SUCCESS [  1.131 s]
[INFO] InteractiveChat-V1_18 .............................. SUCCESS [  8.512 s]
[INFO] InteractiveChat-V1_18_2 ............................ SUCCESS [  8.423 s]
[INFO] InteractiveChat-V1_19 .............................. SUCCESS [ 13.318 s]
[INFO] InteractiveChat-V1_19_3 ............................ SUCCESS [ 41.551 s]
[INFO] InteractiveChat-V1_19_4 ............................ SUCCESS [ 11.559 s]
[INFO] InteractiveChat-V1_20 .............................. SUCCESS [  3.767 s]
[INFO] InteractiveChat-V1_20_2 ............................ SUCCESS [  7.677 s]
[INFO] InteractiveChat-V1_20_3 ............................ SUCCESS [  5.374 s]
[INFO] InteractiveChat-V1_20_5 ............................ SUCCESS [  8.569 s]
[INFO] InteractiveChat-V1_20_6 ............................ SUCCESS [  5.939 s]
[INFO] InteractiveChat-V1_21 .............................. SUCCESS [  5.199 s]
[INFO] InteractiveChat-V1_21_1 ............................ SUCCESS [  4.036 s]
[INFO] InteractiveChat .................................... FAILURE [06:57 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:16 min
[INFO] Finished at: 2024-10-21T21:16:17+00:00
[INFO] Final Memory: 81M/336M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project InteractiveChat: Could not resolve dependencies for project com.loohp:InteractiveChat:jar:4.2.12.0: Could not find artifact com.comphenix.protocol:ProtocolLib:jar:all:5.3.0-SNAPSHOT in placeholderapi (https://repo.extendedclip.com/content/repositories/placeholderapi/) -> [Help 1]
```

**Comment by new1271** [comment]
@NotAlexNoyle problem fixed

**Comment by NotAlexNoyle** [comment]
Working now. Thanks!

**Pull request merged**
