### PR TITLE
Update ExcellentEnchants and some other dependencies

### PR DESCRIPTION
**Pull request by Snewmy**
Fixed ExcellentEnchants support

### CODE REVIEW

**Comment by SmallSansSerif** [comment]
Can this get merged please? I can't run later versions of IC until this hook is working again.

**Comment by SmallSansSerif** [comment]
It might be. You already added support for new version? Just didn't see it in changelog.

**Comment by LOOHP** [comment]
If it is the same with that PR, then what you need updated should already be in the latest build.

**Comment by Snewmy** [comment]
> If it is the same with that PR, then what you need updated should already be in the latest build.

Loop, items in the chat were not showing any enchants at all, until downgrading adventureapi from snapshot to latest release (i think 4.16).

**Pull request closed without merging**
